apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quarkus-certificate
spec:
  secretName: quarkus-certificate-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - ibmoffices
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - server auth
    - client auth
  dnsNames:
    - '*.ibmoffices.svc'
    - '*.ibmoffices.svc.local'
    - '*.ibmoffices.svc.local.cluster'
  issuerRef:
    name: quarkus-ss-issuer
