apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ibmoffices-servicemonitor
  namespace: ibmoffices
spec:
  endpoints:
  - interval: 30s
    targetPort: 8080
    path: /q/metrics
    scheme: http
  selector:
    matchLabels:
      app: ibmoffices