apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-app-monitor
  name: prometheus-app-monitor
  namespace: ibmoffices
spec:
  endpoints:
  - interval: 30s
    targetPort: 8443
    path: /q/metrics
    scheme: https
  selector:
    matchLabels:
      app: ibmoffices