apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibmoffices-app
  namespace: openshift-gitops
  labels:
    group: applications
spec:
  destination:
    namespace: ibmoffices
    server: https://kubernetes.default.svc
  project: ibmoffices
  source:
    path: ./envs/ibm-vpc/non-prod/app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true