apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-t5h01t
  namespace: ibmoffices
spec:
  resources:
    kubernetesResource:
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
            containers:
              - env:
                  - name: TLS_CERT
                    valueFrom:
                      secretKeyRef:
                        key: tls.crt
                        name: eventlistener-certificate-secret
                  - name: TLS_KEY
                    valueFrom:
                      secretKeyRef:
                        key: tls.key
                        name: eventlistener-certificate-secret
                name: ''
                resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: trigger-template



