kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton-workspace
  namespace: ibmoffices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: PATCHED_BY_KUSTOMIZE
  volumeMode: Filesystem